- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - pacman-contrib
    state: latest

- name: system setup | cron | start and enable pacchace daemon
  tags: paccache
  become: true
  command:
    cmd: "systemctl enable paccache.timer"
