- name: install packages
  package:
    name:
      - htop
      - htop
      - lf
      - lazygit
      - lazydocker
      - fzf
      - ripgrep
      - zsh 
      - alcritty
      - curl
      - xclip
      - firefox
