- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:Kristmh/dotfiles'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    update: yes
    accept_hostkey: yes
    version: main
    key_file: $HOME/.ssh/id_ed25519
  tags:
    - install
    - dotfiles
    - stow
